---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install yamllint
        run: pip install --user yamllint
      - name: Run yamllint
        run: ~/.local/bin/yamllint -c .yamllint.yml --strict .
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: fkautz/shell-linter@v1.0.1
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_CONTAINER: golangci/golangci-lint:v1.23.2
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Pull golangci-lint docker container
        run: docker pull ${GOLANGCI_LINT_CONTAINER}
      - name: Run golangci-lint
        run: docker run --rm -v $(pwd):/app -w /app ${GOLANGCI_LINT_CONTAINER} golangci-lint run

  excludeFmtErrorf:
    name: exclude fmt.Errorf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Exclude fmt.Errorf
        run: |
          if grep -r --include=*.go fmt.Errorf . ; then
           echo "Please use errors.Errorf (or errors.New or errors.Wrap or errors.Wrapf) as appropriate rather than fmt.Errorf"
           exit 1
          fi

  restrictNSMDeps:
    name: Restrict dependencies on github.com/networkservicemesh/*
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Restrict dependencies on github.com/networkservicemesh/*
        run: |
          for i in $(grep github.com/networkservicemesh/ go.mod |grep -v '^module' | sed 's;.*\(github.com\/networkservicemesh\/[a-zA-z\/]*\).*;\1;g' | sort -u);do
            if [ "${i}" != "github.com/networkservicemesh/sdk-vppagent" ] && [ "${i}" != "github.com/networkservicemesh/sdk" ] && [ "${i}" != "github.com/networkservicemesh/api" ]; then
              echo Dependency on "${i}" is forbidden
              exit 1
            fi
          done

  checkgomod:
    name: check go.mod and go.sum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - run: go mod tidy
      - name: Check for changes in go.mod or go.sum
        run: |
          git diff --name-only --exit-code go.mod || ( echo "Run go tidy" && false )
          git diff --name-only --exit-code go.sum || ( echo "Run go tidy" && false )
  license:
    name: license header check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Install go-header
        run: 'go get github.com/denis-tingajkin/go-header@v0.2.2'
      - name: Run go-header
        run: |
          eval $(go env)
          ${GOPATH}/bin/go-header
  excludereplace:
    name: Exclude replace in go.mod
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
      - name: Exclude replace in go.mod
        run: |
          grep ^replace || exit 0
          exit 1
  captureRunEnv:
    name: Capture CI Run Env
    runs-on: ubuntu-latest
    steps:
      - run: printenv
  gogenerate:
    name: gogenerate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Generate files
        run: go generate ./...
      - name: Check for changes in generated code
        run: |
          git diff -- internal/imports/imports.go || ( echo "Rerun go generate ./... locally and resubmit" && false )
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build .
      - run: docker run  --privileged --rm $(docker build -q --target test .)
      - name: Find merged PR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ github.token }}
      - name: Publish Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && success() && steps.findPr.outputs.number
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ github.token }}
          tag: |
            latest
            "commit-${{ github.sha }}"
            "pr-${{ steps.findPr.outputs.pr }}"

  automerge:
    name: automerge
    runs-on: ubuntu-latest
    needs:
      - docker
    if: github.actor == 'nsmbot' && github.base_ref == 'master' && github.event_name == 'pull_request'
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Fetch master
        run: |
          git remote -v
          git fetch --depth=1 origin master
      - name: Only allow go.mod and go.sum changes
        run: |
          find . -type f ! -name 'go.mod' ! -name 'go.sum' -exec git diff --exit-code origin/master -- {} +
      - name: Automerge nsmbot PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: nsmbot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
